# Mod
mod_id=ardastuff
mod_name=ArdaStuff
mod_description=Tweaks and utilities for ArdaCraft.
mod_version=1.3.0

# Minecraft (https://modmuss50.me/fabric.html)
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10

# Fabric
fabric_loom_version=1.11-SNAPSHOT
fabric_loader_version=0.17.2
fabric_api_version=0.92.6+1.20.1

# Create
create_version = 0.5.1-f-build.1417+mc1.20.1

# LazyDFU
lazydfu_version = 0.1.3

# Gradle
java_version=17
maven_group=com.ardacraft
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2G